### ISSUE TITLE
Remove js-tracer from revm-inspectors

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#1006]
Do we need it? Feature `js-tracer` brings a JS Compiler/VM as a dep

**Comment by eyusufatik** [comment]
is this usable right now? @ercecan  if not let's remove it

**Comment by ercecan** [comment]
We are actually not using js tracer right now + the feature flag is not enabled anyways so we're good
```rust
GethDebugTracerType::JsTracer(_code) => {
    // This also requires DatabaseRef trait
    // Implement after readonly state is implemented
    return Err(EthApiError::Unsupported("JsTracer"));
}
```

**Comment by yaziciahmet** [comment]
Erce is right. js-tracer is the default feature of revm-inspectors, and many some other reth dependencies has it enabled as default as well, but we have disabled all the default-features for revm, reth, and alloy dependencies. This issue can be closed.

**Comment by kpp** [comment]
Not really. It's nice to remove `boa` from Cargo.lock because it's never used.
