### ISSUE TITLE
Adjust diff size calculation for l1 fee compensation

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#1035]
Normally when an accounts balance changes we should only write the 20 byte address as key and 32 byte balance value to the state diff, however in our current implementation when we update any single one of the following fields like balance, nonce or code hash, even though only one of them changes, we write all of them to the state diff [#999].

We need to compensate this in L1 fees by adjusting our diff size calculation.

For example right now we only add the balance if balance changes of an account , but we should also be adding the size of code_hash and nonce.
So when a `balance` changes add extra `size_of(code_hash) + size_of(nonce)`
when a `nonce` changes add extra `size_of(balance) + size_of(code_hash)`
when a `code_hash` changes add extra `size_of(balance) + size_of(nonce)`

**Comment by eyusufatik** [comment]
Not only that but the keys are longer too.

we should sit down and print out key lengths then use that in our calculation.

looks like one of the challenges on the road to mainnet will be optimizing key lengths 😄
