### ISSUE TITLE
DA: get_relevant_blobs_from_txs must accept &[Tx] not Vec<Tx>

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#1040]
To avoid unnecessary copy up to 4mb of data in zk context.

**Comment by SIDHARTH20K4** [comment]
hey @kpp would you like to fix this issue?

**Comment by kpp** [comment]
@SIDHARTH20K4 take it if you like

**Comment by SIDHARTH20K4** [comment]
@kpp 
could you tell me how do i approach this problem?

**Comment by kpp** [comment]
`get_relevant_blobs_from_txs` is not called in a zk context
