### ISSUE TITLE
Don't panic, return Err on sov-tx deserializtion or signature errors

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1061]
see this issue in codebase

**Comment by rakanalh** [comment]
Can you please link to the line mentioning the issue?

**Comment by eyusufatik** [comment]
There is panic's here:
https://github.com/chainwayxyz/citrea/blob/578594afd7b0edb66fa2735d31b7592db3ef4c9e/crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/stf_blueprint.rs#L84


though this issue can be done closer to a planned fork, since it'll cause a fork.
