### ISSUE TITLE
output L2 heights on zk proof

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1066]

**Comment by rakanalh** [comment]
Do you mean the sequencer commitment ranges? aren't they already in?

**Comment by eyusufatik** [comment]
yes actually the heights can be obtained from 

`da_root_hash` + `preproven_commitments` + `sequencer_commitments_ranges`

so I'm closing this issue, we don't really get an advantage from outputting the L2 ranges directly.
