### ISSUE TITLE
Get rid of inlined macro in risc0-bonsai host.rs

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1097]

**Comment by rakanalh** [comment]
If you're referring to `retry_backoff_bonsai` i think it doesn't hurt to keep it since it cuts down some boilerplate for retries in multiple places.

**Comment by eyusufatik** [comment]
> If you're referring to `retry_backoff_bonsai` i think it doesn't hurt to keep it since it cuts down some boilerplate for retries in multiple places.

Yes macro is really useful. I was talking about two places in that file with a slightly modified expanded version of the macro right inside the functions. That's because I couldn't really fix the var moved errors. :)
