### ISSUE TITLE
Non-Graceful shutdown recovery

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1184]
Currently if a node is shutdown there is a very small chance we fail to save stuff to database. And on restart, the node can't sync. This happened to me several times. Wiping db and re-syncing solves the problem but it's not sustainable at all. What if it happens to the seqeuncer

**Comment by rakanalh** [comment]
This is IMO solvable by atomicity. The execution could reach to any point in the code where some partial data is written about L1 / L2 blocks and/or commitments but incomplete.

We need to implement a atomic execution where recording information about an L2 block (example) is entirely written and committed or reverted back to the original state (in case of shutdown).

We'll need some effort to figure out how to do that.

**Comment by rakanalh** [comment]
Related: https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/942
