### ISSUE TITLE
Refactor `start_rollup` test helper

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1202]
It's become a mess

**Comment by rakanalh** [comment]
Solution would be to adopt the bitcoin e2e implementation which supports MockDA IMO.

**Comment by eyusufatik** [comment]
> Solution would be to adopt the bitcoin e2e implementation which supports MockDA IMO.

let's make this a longer term target 👍 

for now ege will refactor start_rollup
