### ISSUE TITLE
DNS resolution issue when attempting to connect to the Bitcoin signet node

### ISSUE THREAD

**Issue by YeagerAI-Bulat** [chainwayxyz/citrea#1218]
## Summary

Critea failed to communicate with the `bitcoind` instance after running for a few hours on a GCP VM (n2d-standard-8) with local NVMe SSD storage. The error indicates a DNS resolution issue when attempting to connect to the Bitcoin signet node.

## Steps to reproduce

1. Set up a GCP VM instance with the following specifications: `n2d-standard-8`, local NVMe SSD, Ubuntu 24.04 LTS.
2. Install and configure Docker, [Critea](https://docs.citrea.xyz/user-guide/run-a-node/docker-compose-setup), following official guide.
3. Allow Critea to run for several hours.
4. Monitor the logs to observe the failure.

## Expected Result

Critea should maintain continuous communication with the `bitcoind` instance and operate without interruptions for an extended period.

## Actual Result

After running for a few hours, Critea logged a warning indicating a failure to send a call to `bitcoind` due to a DNS resolution error. The connection attempt failed after 11 retries.

Error message, repeated many times:
```
{"timestamp":"2024-09-23T14:29:17.620404Z","level":"WARN","fields":{"message":"Failed to send a call to bitcoind","error":"reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"citrea-bitcoin-signet\")), port: Some(38332), path: \"/wallet/citrea\", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: Temporary failure in name resolution\" })) }","attempt":11},"target":"bitcoin_da::rpc"}
```

## Additional Information

- GCP VM: n2d-standard-8, Ubuntu 24.04
- GCP Local NVMe SSD Disk, 375 GB

**Comment by YeagerAI-Bulat** [comment]
Both containers have crashed again after I have tried to run them again. I have started docker compose, it was running fine for 7 hours until now, and crashed:
```
docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS                        PORTS                                       NAMES
8ed2dfd3766e   chainwayxyz/citrea-full-node:devnet        "./run.sh"               8 hours ago   Exited (255) 19 seconds ago   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   full-node
9a25596fcb98   chainwayxyz/citrea-bitcoin-signet:devnet   "/usr/local/bin/entr…"   8 hours ago   Exited (1) 16 minutes ago                                                 bitcoin-signet
```
[bitcoin-signet container logs](https://app.warp.dev/block/wUlLi0ZOOLiLxUDVRR1jrX)
[full-node container logs](https://app.warp.dev/block/0hXSV3feHlG33LemDPLPg7)

**Comment by eyusufatik** [comment]
you are using devnet nodes.

please start using testnet nodes. the run docs have just recently been pushed.

**Comment by YeagerAI-Bulat** [comment]
@eyusufatik Could you share a link to the updated docs?
Thanks

**Comment by YeagerAI-Bulat** [comment]
I've tried to follow [this guide](https://github.com/chainwayxyz/citrea/blob/nightly/docs/run-testnet.md), `TL; DR: I want to run it ASAP` and after running it for a few hours got these errors:
[full-node logs](https://app.warp.dev/block/vzP1zqOeckVk6SgqUfBKPG)
[bitcoin-testnet4 logs](https://app.warp.dev/block/3VwEOl9kIM079EwhmyjtSo)

**Comment by eyusufatik** [comment]
> I've tried to follow [this guide](https://github.com/chainwayxyz/citrea/blob/nightly/docs/run-testnet.md), `TL; DR: I want to run it ASAP` and after running it for a few hours got these errors: [full-node logs](https://app.warp.dev/block/vzP1zqOeckVk6SgqUfBKPG) [bitcoin-testnet4 logs](https://app.warp.dev/block/3VwEOl9kIM079EwhmyjtSo)

it seems your bitcoin node is syncing **very** slowly. are you sure allocate your system resources to docker correctly?

**Comment by YeagerAI-Bulat** [comment]
I'm using default docker setup and n2d-standard-8 Google cloud VM with a locally attached NVMe SSD and XFS filesystem. CPU and RAM utilization was comparatively low, around 10-20%.

**Comment by eyusufatik** [comment]
closing this issue. pls open support ticket in discord

**Comment by YeagerAI-Bulat** [comment]
Dunno why, but my status is Read Only for 30 days on your discord server🤨
