### ISSUE TITLE
Upgrade dependencies (risc0, reth, alloy etc)

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1292]
We can only upgrade some of the traits through forks. The first one's that I can think of:
- `risc0-*`
- `alloy-primitives`, `reth-primitives` --> basically anything that goes to non native EVM and other crates used inside guest codes.

**Comment by ercecan** [comment]
Now that risc0 supports rust 1.81 and it is updated with #1488 we can also update reth and other dependencies.
Latest version of reth with rust 1.81 is v1.1.0 so we can use that
