### ISSUE TITLE
Risc0 merge host and guest code into a single citrea crate

### ISSUE THREAD

**Issue by yaziciahmet** [chainwayxyz/citrea#1341]

**Comment by rakanalh** [comment]
I was going to suggest this in your #1326 PR. Specifically, `bin/citrea/provers/risc0`

**Comment by yaziciahmet** [comment]
I rolled back some commits in #1326 due to the fact that it changes the risc0 method ids and will require fork. I already laid down the base for easily migrating into a single crate by properly feature-gating dependencies in risc0-bonsai. Should be relatively easy to migrate once we are ready to have a fork.

**Comment by eyusufatik** [comment]
closed by #1411
