### ISSUE TITLE
L1 syncer

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1354]
This is to be implemented in a separate repository by importing `citrea` and `citrea-e2e`.

We want to make sure we can rebuild state from state diffs we send to DA.

This CLI:
- Has connection to a Bitcoin node.
- Knows method IDs for our forks.
- Its only purpose is to build our storage tree.

It scans Bitcoin for our batch proofs, verifies them, records them to some local DB (I can explain why we record later), and applies the state diffs from the proofs to its own storage.

We can't test this against testnet yet, as we do proof sampling. However, by importing `citrea-e2e` we can set up Citrea, run it for some time while running random EVM transactions, than try to rebuild the chain from the diffs that land on regtest.

This is very important to test our state diffs, and it might also serve some users too.

**Comment by kpp** [comment]
Another way is to add a metadata for BatchProof to include method_id and the id of the proving system (e.g. either risc0 or sp1). So when syncer sees a batch proof, it checks if it has the required elf/method. If it's not found - try to find it on github releases.

Also we will need to provide risc0 and sp1 method binaries (elfs) as a build artifact when we publish a new release.

**Comment by eyusufatik** [comment]
closing this issue as we've already implemented most of the l1 syncer and now working on seperate issues. I'll be auto adding l1-syncer issues to here for tracking purposes
