### ISSUE TITLE
E2E flaky: test_sequencer_transaction_chaining

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#1370]
## Summary

```
Error: assertion `left == right` failed: TX6 should reference TX5's output
  left: 02f76e3ee9af4b61e1c7df3d3b123ebf9cdfdd160c586c4497ce06ff8e2679ff
 right: 23e31578a08505ae283919166fdbb0b2202ab8f86066b7bb0e8ea0c8a7d324e5
 ```
 
 ```
 --- TRY 2 STDERR:        citrea::all_tests bitcoin_e2e::tx_chain::test_sequencer_transaction_chaining ---
Error: assertion `left == right` failed: TX6 should reference TX5's output
  left: 33fb584f5a841e0344d7d2f89427cf567e36514ba48ef305447649f4425a7331
 right: d20d4077c309374b81262c8253dd6dfc851c7d1257e66452152f1b582ce0e19d
 ```
 
 https://github.com/chainwayxyz/citrea/actions/runs/11461889179/job/31892011158#step:11:331

**Comment by jfldde** [comment]
This one should really not be flaky since reveal should always use commit output

**Comment by jfldde** [comment]
Made an incorrect assumption based off error indexes.
Turns out we start from 2 (skipped first coinbase but does not make much sense, I'l amend), so this failure is actually using reveal output for commit post restart. 
Looking into it
