### ISSUE TITLE
Access storage in read only mode

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#146]
For #32 we have to implement Revm's DataBaseRef trait. 

Which requires immutable borrowing of self.

However we can only access storage with mutable references (WorkingSet saves every read and write).

We need to access storage without modifying anything.

Checkout branch `orkun/overrides` file `module-system/module-implementations/sov-evm/src/evm/db.rs`.

Cannot implement necessary trait because every StateValue/Map/Vec expects a mutable WorkingSet, while self is borrowed immutably.

TODOs

- [ ] Figure out how to read storage with immutable workingset or something else.

**Comment by rakanalh** [comment]
AFAIU, this was needed to implement: https://github.com/chainwayxyz/citrea/issues/1267

No longer needed.

**Comment by rakanalh** [comment]
@eyusufatik up to you if you want to close this ticket. If you don't, we should merge the `DatabaseRef` PR to close it.
