### ISSUE TITLE
Update `selfdestruct` according to Cancun upgrade

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1461]
selfdestruct behaviour changed in the dencun / cancun upgrade. we also have to update our DbCommit implementation to reflect the changes. keep in mind we still have to support activation prior to cancun.

see EIP describing the change https://eips.ethereum.org/EIPS/eip-6780

keep in mind, the same tx code deletion is probably handled by revm itself. but pls double check.

**Comment by kpp** [comment]
Probably this is already implemented: https://github.com/chainwayxyz/citrea/blob/79a1bb5df6c5790a8aa542216eac9f77efa574fd/crates/evm/src/evm/handler.rs#L492

**Comment by eyusufatik** [comment]
> Probably this is already implemented:
> 
> https://github.com/chainwayxyz/citrea/blob/79a1bb5df6c5790a8aa542216eac9f77efa574fd/crates/evm/src/evm/handler.rs#L492

No it’s just a note for enabling cancun in the future 😄
