### ISSUE TITLE
Benchmark and activate kzg feature of evm

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1462]
Take a look at how revm runs kzg commitment verification. And create benchmark.

Risc0 mentioned if we can use the c-kzg batch verify API we get a good cycle reduction.

**Comment by ercecan** [comment]
In my benchmarks to calculate how many cycles it takes for point eval precompile to run in risc0 guest with c-kzg I saw:
single blob verification costs around 90 million cycle

batch blob verification did not work, errored out
You can also try to run the example below to see the error:
https://github.com/chainwayxyz/c-kzg-bench

Same example but with kzg-rs did cost 286 million cycles for single verification on risc0

**Comment by eyusufatik** [comment]
since we've already decided on not to activate point eval precompile I'll be closing the issue
