### ISSUE TITLE
Fork1 activation tests

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1464]

**Comment by ercecan** [comment]
- [x] Test dencun activation, tstore tload operations, test before and after fork to see if it works as it is supposed to
- [x] Activate dencun ef tests and see which are possible to fix/adjust to our rules

**Comment by eyusufatik** [comment]
> Activate dencun ef tests and see which are possible to fix/adjust to our rules

this is represented in #1463 

see here for different things activated in dencun:

https://wazirx.com/blog/a-breakdown-of-eips-included-in-the-dencun-upgrade-2024/

(not all might apply to us)

and then write here what tests need to be written

**Comment by ercecan** [comment]
According to eips in dencun taken from [here](https://wazirx.com/blog/a-breakdown-of-eips-included-in-the-dencun-upgrade-2024/)

- ~~1 EIP-7514: “The Gatekeeper”~~
- [x] 2 EIP-1153: “The Memory Magician” Test this => transient storage
- ~~3 EIP-4788: “The Bridge Builder”~~
- ~~4 EIP-4844: “The Luggage Carrier”~~
- [x] 5 EIP-6780: “The Code Keeper” Test this => this proposal restricts SELFDESTRUCT usage to the creating contract
- [x] 6 EIP-5656: “The Data Dynamo” Test this => introduces the MCOPY
- ~~7 EIP-7044: “The Exit Maestro”~~
- ~~8 EIP-7045: “The Time Extender”~~
- ~~9 EIP-7516: “The Price Scanner”~~

**Comment by eyusufatik** [comment]
For 9, unfortunately we cant change the behaviour of revm crate, so that opcode will return 1. That's also what optimism does so imo we are ok.

**Comment by eyusufatik** [comment]
- [x] (implemented in e2e rn) test genesis -> fork1 self.code -> self.offchain_code transition
- [x] test if call to point eval precompile reverts

**Comment by eyusufatik** [comment]
I think there is no more tests we should write. except for maybe prover switch ELFs test but I'm going to create an issue for that.
