### ISSUE TITLE
Prune ledger db down to latest state version

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#1550]
I have taken a snapshot from one of our full nodes to sync to ngihtly branch, after that I saw that some ledger db tables needed migrations because of table name changing, so I made tthose migrations. 
After fixing that I saw this error: 
`Root node not found for version 3114265`, this occurs because ledger db's head soft confirmation number is not the same as the states version, this is probably because when the snapshot was taken the state was not done updating all this information for some reason.

To fix this, we can implement a pruning system that will prune down the ledger db and the accessory state to the latest version of state.

**Comment by rakanalh** [comment]
Related: https://github.com/chainwayxyz/citrea/issues/1194

**Comment by eyusufatik** [comment]
this was solved with handling kill signals so I'm closing the issue
