### ISSUE TITLE
Decide on compile time env vars for guests

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1566]

**Comment by jfldde** [comment]
Can probably put what we need behind cargo flag in line with https://github.com/chainwayxyz/citrea/pull/1554 and then set whatever we need there

**Comment by eyusufatik** [comment]
## Light client
- l2 genesis root
- batch proof method id —> will open issue about how this is going to be updated
- batch prover da pubkey


## Batch proof
- fork list --> by making this constant in the batch proof, we'll be able to have these as config files in nodes. this will help a lot with testing
- sequencer_public_key
- sequencer_da_public_key
