### ISSUE TITLE
Implement start from L1 height for light client prover 

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1654]

**Comment by eyusufatik** [comment]
This is already implemented. 😓

**Comment by rakanalh** [comment]
This one is already done:

https://github.com/chainwayxyz/citrea/blob/af3713c96b4352020717593fd14e9c20a18dd827/crates/light-client-prover/src/runner.rs#L148-L152

Where this value is read from config in case we haven't scanned L1 blocks in the light client before, and is passed to the DA block handler:
https://github.com/chainwayxyz/citrea/blob/af3713c96b4352020717593fd14e9c20a18dd827/crates/light-client-prover/src/da_block_handler.rs#L85

And the sync starts from there.
