### ISSUE TITLE
Improve TransactionRequest to TypedTransactionRequest conversion

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#199]
In `sov-ethereum/src/lib.rs`, the conversion from `TransactionRequest` to `TypedTransactionRequest` is very ugly and prone to bugs bc of unwraps.

Once [corresponding reth issue](https://github.com/alloy-rs/alloy/pull/183#issuecomment-1928161285) is resolved update it.

**Comment by rakanalh** [comment]
Is this still valid?

**Comment by eyusufatik** [comment]
> Once https://github.com/alloy-rs/alloy/pull/183#issuecomment-1928161285 is resolved update it.

tracked in this now https://github.com/alloy-rs/alloy/pull/190

> Is this still valid?

yes

**Comment by eyusufatik** [comment]
sorry this is not valid since we disabled `eth_sendTransaction`
