### ISSUE TITLE
Add Hive tests to CI

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#230]
TODOs:

- [x] Figure out which hive tests we need.
- [x] Figure out a place to put the hive tests.
- [x] Make sure everything runs correctly against a sequencer - full node set up. (Test runner talks to full node not sequencer)
- [x] Add hive test to CI

**Comment by rakanalh** [comment]
Is this ticket already done with #290? if so, it can be marked as done.
