### ISSUE TITLE
Add L1 fee to eth_call

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#240]
L1 fee was implemented in https://github.com/chainwayxyz/secret-sovereign-sdk/pull/219 however there was no L1 fee handler added to Evm::inspect.

TODOs:

- [ ] Combine TracingInspector and CitreaHandlerExt together
- [ ] Impl GetInspector and CitreaHandlerContext for that combined struct
- [ ] Register citrea_handle_register before inspector_handle_register

**Comment by eyusufatik** [comment]
No fees on eth_call as resolved in #241
