### ISSUE TITLE
Mock DA: Db Connector depends on Cargo

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#252]
Mock Da Db Connector has a function dependent on Cargo:
```rust
fn workspace_dir() -> PathBuf {
    let output = std::process::Command::new(env!("CARGO"))
        .arg("locate-project")
        .arg("--workspace")
        .arg("--message-format=plain")
        .output()
        .unwrap()
        .stdout;
    let cargo_path = Path::new(std::str::from_utf8(&output).unwrap().trim());
    cargo_path.parent().unwrap().to_path_buf()
}
```
When I was trying to run the executable on an environment without rust toolchain I had an error because of this. We should find a better way to get the working directory. 
First thing that comes to mind is giving it as an **env** variable.

**Comment by rakanalh** [comment]
This has been dealt with in https://github.com/chainwayxyz/citrea/pull/626/files
