### ISSUE TITLE
EVM: Figure out a way to divide L1 fees between transactions

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#267]
Currently every transaction pays for its own state diff. So they cannot benefit from multiple transactions affecting the same slots reducing the cost for a single tx.

We need to figure out how to divide this among all txs in the same soft confirmation block.

Also when we write to DA, we benefit from this too, so users should benefit as well.

**Comment by eyusufatik** [comment]
we can utilize a system transaction at the end of a block to this actually.

Or even better at the beginning of a new L1 block, along with set block hash system transactions. but that tx would be too big probably.

anyways, on the first case:
- `CitreHandler` keeps track of an in block "diffSize"  and reimburses tx senders at the end of the block through a single tx over a smart contract.

**Comment by eyusufatik** [comment]
In a state diff rollup there is no "true" way to split L1 fee among transacters, so we'll have to make simulations and have a statistical system that lower costs for accounts optimistically.

This simulation can be done over Ethereum blocks for different range of heights, keeping track of the percentage of the nodes on the state tree that were updated more than once. Then we'd be able to apply a discount to all L1 fees paid by this percentage, making it cheaper for every transaction.

**Comment by kpp** [comment]
Stat was collected, the discount was applied
