### ISSUE TITLE
EVM: Do something when tx.signature doesn't match

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#278]
https://github.com/chainwayxyz/secret-sovereign-sdk/blob/0254e2e71717b6b555ee74ebc1df01d8d1c92ddd/module-system/module-implementations/sov-evm/src/call.rs#L42

Now we silently ignore txs with invalid signature. We have to report/do something about it.

**Comment by eyusufatik** [comment]
any tx that results with this should invalidate the L2 block actually. so the sequencer itself should detect if something like this happens and remove that from it's block. -- which shouldn't really happen bc the mempool does this check, yet again we can impl. something for this.

**Comment by rakanalh** [comment]
Based on a conversation with @eyusufatik. We're not going to implement this since sequencer already doesn't put such a tx in the soft confirmation.

Relaying decision to close this to him
