### ISSUE TITLE
Evm: begin_soft_confirmation_args too many args

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#341]
There are too many args in that function and it's hard to look at the code. Maybe we should create a struct for args.

**Comment by eyusufatik** [comment]
good catch 
we can pass in the whole HookSoftConfirmationInfo struct (the thing passed to the runtime hooks)
we already dot that to soft confirmation rule enforcer

**Comment by eyusufatik** [comment]
Handled in #445
