### ISSUE TITLE
EVM: recompile code for predeployed contracts

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#353]
https://github.com/chainwayxyz/citrea/blob/be84a2aaf368b019ce99b0ec0c92db53f2cd4dc9/crates/evm/src/evm/system_contracts/out/L1BlockHashList.sol/L1BlockHashList.json#L1

Predeployed contracts were introduced in https://github.com/chainwayxyz/citrea/pull/346. L1BlockHashList was compiled by hands and put to repo. In case the code of contract is changed (and bytecode is changed as well) we need some kind of trigger/warning/recompilation.

**Comment by eyusufatik** [comment]
@okkothejawa is this closed by #864 ?

**Comment by okkothejawa** [comment]
There's no warnings or automation yet, still anyone modifying the contract should run `make genesis` and modify the tests.

**Comment by eyusufatik** [comment]
there is a ci check now.
