### ISSUE TITLE
SoftConfirmationRuleEnforcer: add rule for da height & hash

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#355]
**Is your feature request related to a problem? Please describe.**
DA height must be same or sequential, DA hash must differ only if DA height differs.

**Describe the solution you'd like**
Store last_da_info=(height, hash), add `fn apply_da_height_rule` and check soft_batch.da_slot_height & da_slot_hash.

**Additional context**

File: crates/soft-confirmation-rule-enforcer/src/hooks.rs

**Comment by eyusufatik** [comment]
should be handled after #873

**Comment by eyusufatik** [comment]
when I think about it, this stuff is actually handled right before running L2 blocks in zk guest.

we can remove those and add them into the soft confirmation rule enforcer module.

However, if we do that that means we'll need to write prev_hash to state, and read it on the next L2 block which is an extra merkle verification in the zk guest. so I'm a little hesitant on this.

**Comment by eyusufatik** [comment]
I now believe these type of things should be handled explicitly in memory if we can, rather than reading and (or) writing to state
