### ISSUE TITLE
evm::web3_rpc_tests use compiler version in runtime

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#375]
## Summary

Research whether we should test rustc version. See https://github.com/chainwayxyz/citrea/actions/runs/8653017088/job/23732699699#step:11:1759

**Comment by eyusufatik** [comment]
I think we can use this issue to use a macro to put in the compiler version in that string.

TODOs:

- [ ] [This crate](https://crates.io/crates/rustc_version_runtime) seems to do what we need. Use it instead of the hardcoded version number in web3_clientVersion
