### ISSUE TITLE
Sequencer: subtract with overflow

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#391]
## Summary

```
thread 'main' panicked at crates/sequencer/src/commitment_controller.rs:82:9:
attempt to subtract with overflow
```

https://github.com/chainwayxyz/citrea/blob/26827d6a1d7f56cfe16d8d37bb5e130a5d475c62/crates/sequencer/src/commitment_controller.rs#L82

That's quite reproducible:

https://github.com/chainwayxyz/citrea/actions/runs/8714255845/job/23904176591?pr=385#step:10:30
https://github.com/chainwayxyz/citrea/actions/runs/8714255845/job/23904465110?pr=385#step:10:30

**Comment by eyusufatik** [comment]
Yes I have noticed this before as well

If there is a single L2 block on an L1 block, while checking if it should commit or not, we get an underflow error I beleive.

**Comment by otaliptus** [comment]
We already have this in the nightly? I pushed this fix to @kpp's branch.

https://github.com/chainwayxyz/citrea/blob/8b6fd82466d308984df0ff919cb2e8d1532786f6/crates/sequencer/src/commitment_controller.rs#L83

May add a comment if you want though. @eyusufatik
