### ISSUE TITLE
Activate Deposit transactions

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#403]
The deposit transactions will be executed as system transactions. (EOAs can execute themselves if they wish to)

The sequencer will choose which da layer transactions (deposits) will be executed by the system signer.

To accomplish this we'll add deposits to the soft confirmation struct.

TODOs:

- [x] Modify DaService trait, add method `get_transaction_inclusion(TransactionId) -> (u64, Vec<Hash>)` types might need to be [u8; 32], not really strict on types here. Leave as todo! in every da service. u64 is block height here.
- [x] Modify DaService trait, add method `get_transaction(TransactionId) -> Vec<u8>` leave as todo! in every da service.
- [x] Add a Vector of Txid's ([u8; 32]) to `UnsignedSoftConfirmaitonBatch`, `SoftConfirmationBatch`, `StoredSoftBatch` and related structs, so the sequencer can choose and supply the deposits to full nodes. (we will implement these deposit selection from the DA layer later.)
- [ ] The full nodes can now receive the deposits to execute, this requires modification on `GetSoftBatchResponse`. Upon receiveng deposit Txid's the full nodes will ask DaService for wtxid mekle proof for these transactions and also use `get_transaction` for every Txid. Keep these info in appropriate data structures.
- [x] Compile `Bridge.sol` and put the `deployedBytecode` in genesis evm.json in address 0x31......2 
- [x] Edit `crates/evm/src/evm/system_events.rs` and add `BridgeInitialize` and `BridgeDeposit` (check `Bridge.sol` for which arguments to supply to these events.
- [x] A match will fail in the same file. Fix that.
- [x] Edit `HookSoftConfirmationInfo`, add field deposits with a type of  `Vec<DepositTransaction>`.
- [x] Define DepositTransaction in the same file with fields `block_height: u64`, `tx_body: Vec<u8>` and `inclusion_proof: Vec<[u8; 32]>`. Might need to be in a different file. Or we can define DepositTransaction to be returned by DA, let's discuss.
- [ ] Modify `StateTransitionFunction::apply_soft_batch()` to accept a vector of deposit transactions. And push deposit transactions down to `HookSoftConfirmationInfo`.
- [ ] Refactor evm `begin_soft_confirmation_hook` to accept `HookSoftConfirmationInfo ` instead of all those args.
- [ ] In `crates/evm/src/hooks.rs` if hook_info.deposit_transactions() is not empty, populate with deposit_transactions.

**Comment by otaliptus** [comment]
Looks like Vec<DepositTransaction> can be defined in state-machine/stf and be used in node/services/da.
