### ISSUE TITLE
Make sequencer testable

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#410]
Currently sequencer produces blocks every two seconds however in tests sequencer publishes blocks by listening to rpc requests. This might cause problems in the future because we cannot test the actual functionality.

We need to find a way to test the sequencer while it is publishing blocks on its own.

**Comment by kpp** [comment]
Uniswap tests are a good candidate for that. Disable L2 block production in CI, tests must pass with your `bin/citrea/configs/mock/sequencer_config.toml` test_mode = false.
