### ISSUE TITLE
Add l1 fee to gas estimation

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#417]
Follow up of https://github.com/chainwayxyz/citrea/issues/398

TODO:
- [ ] Similar to Arbitrum, somehow make fee endpoints add the L1 fee rate to the estimations. (open another issue for this)

See https://github.com/OffchainLabs/nitro/blob/v2.2.5/nodeInterface/NodeInterface.go#L511 and https://docs.arbitrum.io/build-decentralized-apps/nodeinterface/reference

**Comment by eyusufatik** [comment]
not to be confused with #420, this issue should somehow add in the L1 fee estimations into the normal gas estimation (or fee rate estimation) so that existing eth libraries and infra knows if a tx will fail due to L1 fees. We have #420 for operations Citrea specific (more precise).
