### ISSUE TITLE
Enhance logging

### ISSUE THREAD

**Issue by otaliptus** [chainwayxyz/citrea#509]
## Description
We need to log a couple more stuff to trace how things pan out better, along with reconsidering the return part.

**Comment by eyusufatik** [comment]
Changing this issue for general refactoring of our logs.

Let's do more & better logs, the tracing library has cool features, let's use them.

Span of this log refactoring includes the following paths and never includes tests:

- [ ] bin/citrea
- [ ] crates/bitcoin-da
- [ ] crates/citrea-stf
- [ ] crates/ethereum-rpc
- [ ] crates/evm
- [ ] crates/sequencer (very important)
- [ ] crates/sequencer-client (don't think much to log here)
- [ ] crates/shared-backup-db
- [ ] crates/soft-confirmation-rule-enforcer
- [ ] crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db
- [ ] crates/sovereign-sdk/full-node/sov-ledger-rpc
- [ ] crates/sovereign-sdk/full-node/sov-stf-runner
- [ ] crates/sovereign-sdk/module-system/module-implementations/sov-accounts
- [ ] crates/sovereign-sdk/module-system/sov-modules-rollup-blueprint
- [ ] crates/sovereign-sdk/module-system/sov-modules-stf-blueprint
