### ISSUE TITLE
How to handle a field in response of Eth_getLogs RPC (field name: 'removed')

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#6]
In the response of eth_getLogs rpc request there is a boolean field called 'removed'. How should we handle this field?
the definition from the source:
```
removed: TAG - true when the log was removed, due to a chain reorganization. false if its a valid log.
```
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterchanges

Currently it is set to false for all logs.

**Comment by ercecan** [comment]
Come back to this after #736 is merged

**Comment by eyusufatik** [comment]
no reorgs on our chain - as long as we build on finalized bitcoin blocks.

so this is irrelevant
