### ISSUE TITLE
Monitoring & Alerts

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#653]
List as provided by @eyusufatik:

- [ ] No block produced in the last 4 seconds
- [ ] No block produced in the last 10 seconds
- [ ] No block produced in the last minute (this should wake us up from our sleep :slightly_smiling_face: )
- [ ] RPC response took more than 250 ms (a simple `eth_blockNumber` rpc call should be enough)
- [ ] RPC response took more than 750 ms (this should wake us up from our sleep also)
- [ ] No new Bitcoin block in the last 5 minutes (valid for our signet of course)
- [ ] Blocks not finalizing in the last 10 minutes (will call `ledger_getSoftConfirmationStatus`, we can talk about how to do this)
- [ ] Blocks not finalizing in the last 10 minutes (will call batch explorer api)
- [ ] No new proven blocks in the last 30 mins (will call `ledger_getSoftConfirmationStatus`)
- [ ] No new proven blocks in the last 30 mins (will call batch explorer api)
- [ ] Batch explorer api not reachable.
- [ ] citrea.xyz not reachable.
- [ ] Bridge backend not reachable.
- [ ] Blockscout not reachable.
- [ ] Mempool.space (our custom signet’s explorer) not reachable.
- [ ] And finally, RPC not reachable (should take us back from death lol. signal like crazy)

**Comment by eyusufatik** [comment]
this is handled in another repo
