### ISSUE TITLE
MockDA: Separate the sender addresses of sequencer and prover

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#672]
Currently in mockda the sender addresses of sequencer and prover are the same, this causes some unnecessary checks when parsing da data and creates confusion

**Comment by kpp** [comment]
We split txs by prefixes, so this issue is no longer valid. see https://github.com/chainwayxyz/citrea/issues/972

**Comment by eyusufatik** [comment]
> We split txs by prefixes, so this issue is no longer valid. see https://github.com/chainwayxyz/citrea/issues/972

this is not about that
