### ISSUE TITLE
Prover Cycle Improvements

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#713]
We need to decrease the cycle counts of our proving opertions

We can look into:
- Serialization and deserialization optimizations
- Updating merkle root verifier in bitcoin DA
- ...

**Comment by kpp** [comment]
Benchmarks for serde were done in https://github.com/chainwayxyz/citrea/issues/705

**Comment by kpp** [comment]
This task was completed. We may open another issue in the future.
