### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#718]
## Summary

Following tests are flaky:
- `sequencer_crash_and_replace_full_node`
- `test_archival_state`
- `test_all_flow`
- `test_gas_price_increase`
- `test_gas_limit_too_high`
- `test_eth_get_logs`
- `test_db_get_proof`
- `test_ledger_get_head_soft_batch`
- `check_commitment_in_offchain_db`

**Comment by kpp** [comment]
https://github.com/chainwayxyz/citrea/issues/646
