### ISSUE TITLE
Prover: Save witness generated data in Ledger DB

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#737]
The prover currently calculates witness data on the fly and uses this data to generate proof.
However, in case of prover failure, we are not going to be able to regenerate the witness data again and therefore we should be able to restore the witness data from DB and generate prove after failure.

**Comment by eyusufatik** [comment]
For every L2 block the prover is running on its state, it should save the generated witness in its DB.

When it encounters a sequencer commitment on DA it can use these witnesses to generate a proof.

This will enable #738
