### ISSUE TITLE
Integration of  Lava Public RPC to Citeria Devnet

### ISSUE THREAD

**Issue by DeanMojo** [chainwayxyz/citrea#771]
The Citeria devnet is currently a bit slow but can be made really fast with the integration of a Lava Network RPC. Several testnets and mainnets have already signed up for an rpc powered by Lava.  This rpc can act as an alternative for users in case the main rpc has faces issues in the near future. Citeria can be an app partner by signing up here - https://www.lavanet.xyz/partnerships

**Comment by eyusufatik** [comment]
please contact info@citrea.xyz for integration requests and proposals. thank you!
