### ISSUE TITLE
Restore RPC `da_publishBlock` for MockDa

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#812]
We need this for CI checks such as `uniswap`, `web3_py` and `ethers_js`

**Comment by eyusufatik** [comment]
I mean they don't necessarily need it.

It would be better if we could test l2 blocks on different l1 blocks on those ci tests

**Comment by eyusufatik** [comment]
I don't think we need this anymore since we test binary running on multiple da blocks on bitcoin e2e tests now.
