### ISSUE TITLE
Test if JournalEntry::StorageChange can happen for the same storage key more than once in single tx

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#838]
```rust
            JournalEntry::StorageChange { address, key, .. } => {
                let account = account_changes.entry(address).or_default();
                account.storage_changes.insert(key);
            }
```

In our EVM handler we use a set to keep track of number of storage slots a tx has changed. If the storage change entry does not happen more than once for a single storage slot, we are better off with an integer to keep track.

@kpp have you looked into this while implementing the handler?

**Comment by kpp** [comment]
I used defensive programming in case if storage can change multiple times. I wasn't able to test it, but I think a contract will be very simple to implement:
```
contract a {
   int b;
   fn c() {
     b+=1;
     b+=1;
   }
}
```

**Comment by eyusufatik** [comment]
ahmet found out the StorageChange is found more than once in the revm journal. so the current aproach is fine.
