### ISSUE TITLE
Bitcoin DA supports "versions"

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#871]
Before we start supporting chunk da transactions, we need a few features and optimizations regarding the way we do DA transactions.
TODOs:

- [ ] Get rid of “tags” in transactions, enforce a certain order.
- [ ] Add 1 byte type descriptor, so that we can have different type of DA transactions. (this can both be utilized for future upgrades) -- by the way let's discuss this. we can have the upgradeability on the DaData struct.
- [ ] The new order for DA transaction fields should be rollup name, da tx type, public key, signature (remind you these are different than bitcoin signatures and public keys), nonce, chunks of 520 bytes of body.

Should be merged before #743

**Comment by kpp** [comment]
In order to distinguish different transactions, we need to define a header, which will affect transaction body.

New bitcoin transaction header:

```
PushBytes(TagType[8 bytes, 6 for rollup name, 2 for transaction type])
```

1. Legacy reveal tx (when blob is less than 400kb):

Type: 0

Body:

```
PushBytes(XOnlyPublicKey)
OP_CHECKSIG
OP_FALSE
OP_IF
PushBytes(signature)
PushBytes(sequencer_public_key)
PushBytes(1; - up to 520-bytes chunk of blob)
...
PushBytes(N; - up to 520-bytes chunk of blob)
OP_ENDIF
PushBytes(8 random bytes)
```

2. Chunk-aggregated reveal tx(when blob is greater than 400kb):

Type: 1

Body:

```
PushBytes(XOnlyPublicKey)
OP_CHECKSIG
OP_FALSE
OP_IF
PushBytes(signature)
PushBytes(sequencer_public_key)
PushBytes(len of chunks [2 bytes in little endian])
PushBytes(1; tx_id [64 bytes])
...
PushBytes(N; tx_id [64 bytes])
OP_ENDIF
```

2. Chunk-aggregated reveal tx(a part of Type-1):

Type: 2

Body:

```
PushBytes(XOnlyPublicKey)
OP_CHECKSIG
OP_FALSE
PushBytes(1; - up to 520-bytes chunk of blob)
...
PushBytes(N; - up to 520-bytes chunk of blob)
```
