### ISSUE TITLE
Research: Guest code borsh - avoid preallocations if possible

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#876]
Follow up of https://github.com/chainwayxyz/citrea/pull/851. What we do in guest code:

1. read len(u64) in LE
2. alloc `Vec<u32>` with the given len
3. read len u32 into that vec
4. cast `Vec<u32>` to &[u8]
5. deserialize from slice

This can be sub-optimal because we alloc a vec in step 2. Borsh is capable of de-serializing from a Reader, avoiding preallocs if possible. Instead a tricky `Read` can be implemented that reads only aligned to 4 data (that's the most optimal way for risc0 - https://dev.risczero.com/api/zkvm/optimization#unaligned-data-access-is-significantly-more-expensive) to bypass the vec. 

Further reading: https://github.com/risc0/risc0/pull/1303

**Comment by yaziciahmet** [comment]
I tried implementing borsh::io::Read, and it gave worst results than our current implementation. I believe we currently have a pretty optimized read implementation based on the following:

Less reads is better than more reads. This is valid 100% considering the total read size remains same. I would even state that less reads is better most of the time than more reads even in the case where less reads read higher amount of bytes in total. Taking this into account, both current and Read implementations read the same amount of bytes. But Read implementation had done much more calls to read vm slots, even though my implementation was reading 32 bytes aligned always.

When reading smh., make sure it is reading 32 bytes and it's multiplicates. And in our usecase, we are doing it so anyways. We are aligning the data to 32 bytes before sending,  and when we are reading, we are reading into Vec<u32>, hence it will always be aligned to 32 bytes. Length prefix is u64, making it 32 bytes aligned as well.

@kpp @eyusufatik let me know if you have any concerns, otherwise we can close this one.

**Comment by kpp** [comment]
We will make a call tomorrow to discuss it.

**Comment by yaziciahmet** [comment]
After discussions with @kpp, we tried to implement an efficient Read buffer to see the results. Even though it wasn't the most optimal implementation there could be, it was optimal enough to see that the cycle difference between implementations is large enough that it won't be closed with further optimizations.

On 1.8 MB of data:
- Current full Vec allocation cycle count: 9_889_235
- Read implementation with temporary buffer cycle count: 39_205_486

**Comment by yaziciahmet** [comment]
Reopening as @kpp thinks there is room for potential improvement. Attaching the reader code:
```rs
const SIZE: usize = 32;

struct HostReader {
    tmp_buff: [u8; SIZE],
    tmp_len: usize,
    tmp_ptr: usize,
    remaining: usize,
}

impl HostReader {
    fn new(total_len: u64) -> Self {
        Self { tmp_buff: [0; SIZE], tmp_len: 0, tmp_ptr: 0, remaining: total_len as usize }
    }
}

impl io::Read for HostReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        if self.remaining == 0 && self.tmp_len == 0 {
            return Ok(0);
        }

        let mut remaining = buf.len();
        let mut buf_ptr = 0;

        // If there is anything in temp buffer, write that first
        if self.tmp_len > 0 {
            let to_copy = self.tmp_len.min(buf.len());
            buf[..to_copy].copy_from_slice(&self.tmp_buff[self.tmp_ptr..self.tmp_ptr + to_copy]);
            self.tmp_len -= to_copy;
            self.tmp_ptr = (self.tmp_ptr + to_copy) % SIZE;

            // If there are still bytes in temp buffer, shift the buffer to contain
            // next elements at the first index
            if self.tmp_len > 0 {
                return Ok(to_copy);
            }

            buf_ptr += to_copy;
            remaining -= to_copy;
        }

        // Read 4-bytes aligned from the env
        let aligned_read_len = (remaining / 4) * 4;
        env::read_slice(&mut buf[buf_ptr..buf_ptr + aligned_read_len]);

        remaining -= aligned_read_len;
        buf_ptr += aligned_read_len;
        self.remaining -= aligned_read_len;

        if remaining > 0 {
            // Check total remaining to see if there is enough to load into temp buffer
            let to_cache = self.tmp_buff.len().min(self.remaining);
            env::read_slice(&mut self.tmp_buff[..to_cache]);
            self.remaining -= to_cache;

            buf[buf_ptr..].copy_from_slice(&self.tmp_buff[..remaining]);
            self.tmp_len = to_cache - remaining;
            self.tmp_ptr = remaining;
        }

        Ok(buf.len())
    }
}
```

**Comment by kpp** [comment]
Yes, it actually works.

```
struct ReadHost {
    remanining: usize,
}

impl std::io::Read for ReadHost {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, std::io::Error> {
        let len = buf.len().min(self.remanining);
        env::read_slice(&mut buf[..len]);
        self.remanining -= len;
        Ok(len)
    }
}

main:

    let len: u64 = env::read();

    let reader = ReadHost { remanining: len as usize };
    let mut bufreader = std::io::BufReader::with_capacity(4*1024, reader);
    
    MyBigStruct::deserialize_reader(&mut bufreader).unwrap()
```





With buf read:

```
[host/src/main.rs:38:5] buf_len = 4210728
WARNING: proving in dev mode. This will not generate valid, secure proofs.
cycles read data = 18446744073709551323
borsh 1.5.1
cycles deserialize = 18446744073703200150
cycles compute len = 18446744073709528021
2024-07-31T14:55:55.855522Z  INFO executor: risc0_zkvm::host::server::exec::executor: execution time: 649.104112ms
2024-07-31T14:55:55.855546Z  INFO executor: risc0_zkvm::host::server::session: number of segments: 17
2024-07-31T14:55:55.855549Z  INFO executor: risc0_zkvm::host::server::session: total cycles: 17301504
2024-07-31T14:55:55.855551Z  INFO executor: risc0_zkvm::host::server::session: user cycles: 6419981
```

Original (read full vec):

```
[host/src/main.rs:38:5] buf_len = 4210728
WARNING: proving in dev mode. This will not generate valid, secure proofs.
cycles read data = 18446744073709261363
borsh 1.5.1
cycles deserialize = 18446744073704160728
cycles compute len = 18446744073709528021
2024-07-31T14:57:00.704670Z  INFO executor: risc0_zkvm::host::server::exec::executor: execution time: 570.669021ms
2024-07-31T14:57:00.704698Z  INFO executor: risc0_zkvm::host::server::session: number of segments: 30
2024-07-31T14:57:00.704701Z  INFO executor: risc0_zkvm::host::server::session: total cycles: 30670848
2024-07-31T14:57:00.704703Z  INFO executor: risc0_zkvm::host::server::session: user cycles: 5749323
```

So it's 2x faster and 2x less memory.

**Comment by kpp** [comment]
Surprisingly the best perf is with BufReader capacity = 4 bytes:

```
2024-07-31T15:13:54.362361Z  INFO executor: risc0_zkvm::host::server::exec::executor: execution time: 459.263ms
2024-07-31T15:13:54.362384Z  INFO executor: risc0_zkvm::host::server::session: number of segments: 14
2024-07-31T15:13:54.362387Z  INFO executor: risc0_zkvm::host::server::session: total cycles: 14680064
2024-07-31T15:13:54.362389Z  INFO executor: risc0_zkvm::host::server::session: user cycles: 3773552
```

**Comment by yaziciahmet** [comment]
I did 2 tests. One with dummy risc0 project with dummy and big data. Other one by running our existing tests with increased proof size. Dummy risc0 project is just serializing and deserializing data and nothing else.

In both of these tests, I tested Vec allocation with the length prefix, which is our current approach, and using `env::stdin()` as reader into the BorshDeserializer.

**Dummy RISC0 Project**

For 1.2 MB of data:

*Vec allocation:*
user cycles: 6_390_347
total cycles: 18_874_368
segments: 18

*Reader*
user cycles: 11_865_835
total cycles: 20_447_232
segments: 20

For 6.3 MB of data:

*Vec allocation:*
user cycles: 34_751_186
total cycles: 104_333_312
segments: 100

*Reader*
user cycles: 64_363_535
total cycles: 113_377_280
segments: 109

**Testing full_node_verify_proof_and_store with Larger Proof Sizes** 

For 1.2 MB of data (400 empty L2 blocks)

*Vec allocation:*
user cycles: 1_066_558_828
total cycles: 1_622_147_072
segments: 1_547

*Reader*
user cycles: 1_064_546_586
total cycles: 1_602_748_416
segments: 1_529

For 2.5 MB of data (800 empty L2 blocks)

*Vec allocation:*
user cycles: 2_177_424_251
total cycles: 3_331_325_952
segments: 3_177

*Reader*
user cycles: 2_173_881_434
total cycles: 3_290_431_488
segments: 3_138

**Results so far**

1. In the case where there is only ser/deserialization, Vec performed much better. But the struct used for testing purposes is random as well (by random I don't mean the data is random, but the struct and it's fields are random)
2. For real test use case, Reader is slightly better, about 1%, but this is not that meaningful improvement to be sure that we will have this improvement every time.

Here is the PR to test stuff out: https://github.com/chainwayxyz/citrea/pull/941

**Comment by yaziciahmet** [comment]
I also managed slim down our guest code to just ser-de `StateTransitionData` to actually see what happens with the struct we are using rather than a random struct, and it seems that read is much more efficient than vec allocation. Here are the results:

20 KB:
	vec alloc
	---------
	user cycles: 193767
	total cycles: 1048576
	segments: 1
	read
	-----
	user cycles: 59768
	total cycles: 524288
	segments: 1

288 KB:
	vec alloc
	---------
	user cycles: 2619601
	total cycles: 9699328
	segments: 10
	read
	----
	user cycles: 936050
	total cycles: 4194304
	segments: 4
	
3.2 MB:
	vec alloc
	---------
	user cycles: 29201468
	total cycles: 107479040
	segments: 103
	read
	-------
	user cycles: 9622696
	total cycles: 42074112
	segments: 41
