### ISSUE TITLE
parse_relevant_inscriptions never checks signature

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#907]
## Summary

The signature of a body of an inscription is never checked. And there is a ParserError::IncorrectSignature that is never constructed.

**Comment by eyusufatik** [comment]
https://github.com/chainwayxyz/citrea/blob/d54cf8354e66cc84832e1f380d5c6fa37e6dd186/crates/bitcoin-da/src/helpers/parsers.rs#L38


It's checked here

**Comment by eyusufatik** [comment]
see my last comment
