### ISSUE TITLE
LedgerDb namespacing for sequencer, node, prover

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#911]

**Comment by yaziciahmet** [comment]
LedgerDB has some tables that are for use for specifically sequencer or prover etc. Having access to these tables could cause confusion into believing that these tables are populated. Some example are : `ProverLastScannedSlot` and `ProofBySlot`. These are only populated in prover but anyone is able to access these tables.

Achievable:
Have some sort of namespacing so access to these tables are limited.
