### ISSUE TITLE
Prover l2 height substraction overflow

### ISSUE THREAD

**Issue by yaziciahmet** [chainwayxyz/citrea#947]
Ran sequencer and a prover with bitcoin-regtest as DA. Spammed L1 blocks to bitcoin. Prover errored with substraction overflow.

It seems error seems to be happening in the following code piece inside CitreaProver::process_l1_block:
```rs
            let first_l2_height_of_l1 = sequencer_commitments[0].l2_start_block_number;
            let last_l2_height_of_l1 =
                sequencer_commitments[sequencer_commitments.len() - 1].l2_end_block_number;

            // If the L2 range does not exist, we break off the local loop getting back to
            // the outer loop / select to make room for other tasks to run.
            // We retry the L1 block there as well.
            if !self.check_l2_range_exists(first_l2_height_of_l1, last_l2_height_of_l1) {
                break;
            }
```
When I logged first and last l2's it was 401 and 100 respectively. My guess is that extract_sequencer_commitments method returns commitments unordered. Didn't confirm this for sure, leaving this as a hint.

**Comment by rakanalh** [comment]
@yaziciahmet If you could please try to reproduce the issue & provide logs and/or backtrace... that would be pretty helpful.

**Comment by yaziciahmet** [comment]
I couldn't reproduce this either. It seems like this is either fixed unintentionally by another pr, or is happening very rarely. It should remain as an open issue until it is either reproduced or proved to be fixed.

**Comment by rakanalh** [comment]
Marking invalid until further notice

**Comment by kpp** [comment]
Closing this for now. Feel free to open a new one later.
