### ISSUE TITLE
Create a profile.proto report for guest code

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#952]
In order to address optimization issues we first need to profile our code to understand bottlenecks.

In order to do that may do the following:

1. dump inputs for guest code
2. create a host-compiled version of our guest code
3. feed it and record perf

step 2 can be done for a real guest code on risc0 vm in order to compare the difference. It will be important for us in the future when we will prepare a test env to compare how changes affect our code execution.

Expected result of this issue - provide a report.pb for host-compiled and? for risc0-vm executed binary.

**Comment by yaziciahmet** [comment]
In order do this best, imo we need what @jfldde mentioned, regtest support within our BitcoinService. It won't be realistic as long as we use MockVerifier in our guest code.

**Comment by kpp** [comment]
https://dev.risczero.com/api/zkvm/install installs binary `r0vm`:

```
kpp@laptop:~$ r0vm --help
RISC Zero zero-knowledge VM executable

Usage: r0vm [OPTIONS] <--port <PORT>|--elf <ELF>|--image <IMAGE>>

Options:
      --elf <ELF>
          The ELF to execute

      --initial-input <INITIAL_INPUT>
          File to read initial input from.
          
          Reads input from stdin if an initial input file is not provided.

      --pprof-out <PPROF_OUT>
          Write "pprof" protobuf output of the guest's run to this file. You can use google's pprof (<https://github.com/google/pprof>) to read it
          
          [env: RISC0_PPROF_OUT=]
```

**Comment by kpp** [comment]
> Here is 300 blocks - 3.7MB

[profile.pb.zip](https://github.com/user-attachments/files/16638211/profile.pb.zip)
