### ISSUE TITLE
Prover pre-calculates size of sequencer commitments

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#965]
We want to avoid sending data over 400kb's to the bitcoin network.

On our rollup this can only happen due to state diffs outputted by the batch proof.

A batch proof basically runs all the soft confirmations commited inside a (or multiple) sequencer commitments found in a finalized DA block.

Our batch proofs have the option to prove a range of sequencer commitments inside a DA block. (think of running only the first one among the 2 found in a DA block.)

A prover can pre-calculate the size of a state diff and decide which commitment(s) to prove. 

Since L2 sync and L1 scanning happens in parallel, there is a few ways a prover can know the state diff size of a given L2 range (which is what the commitments commit to):

1. Save state diffs of individual L2 blocks in its db, merge when needed.
2. Prover already saves Witness (trace of get sets to the state db), find a way to convert these to state diffs so we don't save (kind of) the same data twice.
3. There is an option to run the zk guest in "simulation" mode, which does not run the ZkVm at all, just invokes the same function ZkVm would call in native mode. We can call this function and simply get the state diff from its output.

When the prover has the ability to get the state diff size of certain ranges of L2 blocks, it can utilize a simple algorithm to select sequencer commitments to prove:

```
let seq_comms be array of sequencer commitments in a DA block

size = MAX_U64;
remaining = []

while calc_diff_size(seq_comms) > MAX_DATA_SIZE:
    remaining.push(seq_comms.pop())

prove(seq_comms)

# repeat above for remaining
```

Note: The prover usually uses only L1 height to record the last "proving" it made. With these changes, it will also need to know (record to DB) the index of the last sequencer commitment it proved.

**Comment by rakanalh** [comment]
A witness contains:
* A witness is a Vec<Vec<u8>> containing hints:
* Previous state root
* Sparse Merkle root for each state access
* Updated proof
* New state root

I don't think there's a way to use the witness to convert to a state diff. That rules out option #3.

I do think that the first option would be the way to go.

**Comment by eyusufatik** [comment]
>That rules out option https://github.com/chainwayxyz/citrea/issues/3.

Do you mean it rules out option 2?
