### ISSUE TITLE
Update inclusion proof

### ISSUE THREAD

**Issue by ercecan** [chainwayxyz/citrea#970]
Currnetly inclusion proof is made up of wtxids, txids and coinbase tx
We can optimize this proof by replacing txids with merkle proof of coinbase to merkle root

**Comment by eyusufatik** [comment]
And the merkle root can be trusted because we can hash the header and get DA block hash. I think we output the da block's hash (the one we are scanning in the zk proof). Leaving it to be verified in the light client proof
